Change code structure of the app
enghamzasalem/whats-gpt-firebase pull request #7
Opened 2023-08-12 18:41 UTC by hsnkh12

I divided the code into distinct modules, each serving a specific purpose:

Controllers: This module is responsible for housing all the business logic of the application.
Storage: In this module, I configured and established a connection with Firebase.
OpenAI: This module handles the configuration and connection to the OpenAI API.
Views: The "Views" module contains all the HTML files, ensuring a clear separation of content.
Config: This module centralizes all the necessary configuration settings required for the application.

Furthermore, I made adjustments to the endpoints. The application begins with the "index" page ("/"), which features a form for adding only the phone number. Upon form submission, the app redirects to the "wp-client/" page. Here, user have the option to input a prompt, then generate a QR code. The request for this operation is executed from the client side using JavaScript, enhancing the flexibility for managing the loading process, and to regenerate QR code quickly each time user wants to change the promt, instead of starting the whole process again.

2023-08-12 20:18 UTC, enghamzasalem requested changes
Seems great; can you make it on staging branch

2023-08-12 20:23 UTC, hsnkh12 commented
> Seems great; can you make it on staging branch



> Seems great; can you make it on staging branch

Done

2023-08-13 08:41 UTC, enghamzasalem approved these changes

2023-08-13 08:42 UTC, enghamzasalem commented
Some modification related to the project arch, thx to @hsnkh12 for making it real ..

2023-08-13 08:42 UTC, merged